apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:XS1f5G++vT/ZUE9gGeKgryhnWQgFdgAlXiv/+0LWTY88rPNUSIeFou77YANlkCg6rGUA7ZunD/+Olf17gc54qjI=,iv:4AjHnIRILhBs+sjv9nBvoNyT3jD5E2LF5eyBAqnSsPc=,tag:snLExxmboaTujg7HQWCKkg==,type:comment]
    #ENC[AES256_GCM,data:/E1E8AK3Ybh9uee5yCS9cx+Zd6Onpq7hYGzZqf3o5uHcSS0gdrKvvKeniJ8=,iv:QL/yx52j/ilNJ/egCzgBBP6h+jx5P32agtRAcS6ZdEM=,tag:D1eSPjrWQeE7OvIR2wNGCQ==,type:comment]
    VIP: ENC[AES256_GCM,data:mOiz/hZ0iW1L5Dn4iA==,iv:BtuyVnRQkcK0vgzpjRi86ILE5VqwNc5aL8/AX2jFABY=,tag:0hqQtO6Pelkhzd3dpqWQgQ==,type:str]
    #ENC[AES256_GCM,data:pSXBis2roahP3+9PwgdiUAORbca0/Yj4qbk=,iv:XmxBj/Tk86hr+kH5TmyC+RPG1aTtVCMHEcUcRhVZ0XU=,tag:kmJ6XVydIdAdCF2evJsUsw==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:RdohoIBeL0Lfhb6RloA=,iv:NljfCJEMbzOGf7wgnDqBxUbTOMsieaCUJbkjkSYT+E0=,tag:XsyEZ1y8vQz3toLFQX5ifg==,type:str]
    #ENC[AES256_GCM,data:n26b2n01SzcuEGbGp/34DEm9bzglFCiSDhvmA3WJwDECrQ==,iv:5zAjLYgIW7+HckH10CFp7tHJMPO30aQnXNzml1sbyeM=,tag:QM+nNQR06WS3J0bA8HYPow==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:DfjOe3bHFqf3cgQO,iv:tMzCxT4tU49I8lxD2RxXa7/3Q/XuzWSxxDqSIY1ISqw=,tag:wWoAHZ43m4CQ35daZ5+wDQ==,type:str]
    #ENC[AES256_GCM,data:Zjb+iIujBuWM7ZXXeEKNyGwqe4Y9hEzjS3g/gU2If/4SU3AKAPPw4kmitTP4XRE=,iv:LK5tsOE6V77anMXpeXzVxpq6og6ye9oqM3SlX53UJCQ=,tag:wWRZnAAkhfcUI/E5Uh8QPw==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:rO+yhtWHmB1us+OVSzlDcYA0byE9xr8mgvn1,iv:Ss2Pv41vsKQCzfxC/HqvezCDILWd3EBb6ENd3AA5BNI=,tag:DG+ZNZ4hyXaZUgIsssuBVQ==,type:str]
    #ENC[AES256_GCM,data:enZQVqNqBThcSQ7Ycq21PuFPCAgiAEWRGLoItyvYuCK6r4XCWgM8qHRkkPXHQVrcU7evnEobyCApBt24r4E5kRc+fbZhIwtIVoI1VLjmjpQ=,iv:xpXuYBWVTgfaYwhsFmoR7u7smv7JmALo6axi0gXRjB0=,tag:etDvhV+PhdEVOwuk/YyAww==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:xxx4jDNmTjl/YyKA7w==,iv:f4W+x2TC51DpqE3ZqQQGrNtXWe5XucpdQ1bKWbgJbJk=,tag:2TAnP9uYusvaSIvmNWHXrQ==,type:str]
    #ENC[AES256_GCM,data:XsanmIR2Ot4UB7sCz6JFcEVYJiQqABnnESGnxmaxzQQvo5Hv0KjBH/3xmQQm43+YEeIwOoZgPsQ=,iv:GqGpip/1FKs0LBbtl14OIv/KCKV4AsjnPbiXdHVMg1M=,tag:O82vXEBpm8z4JUR8fatmqA==,type:comment]
    #ENC[AES256_GCM,data:ivpRRA0oXynYB0x5RqAu1PUmPf/rLU126g==,iv:eEZ0O5d81yK5EqwZ8t6tRGRwMywJJONdRzlXkG6xpXE=,tag:ebmfqc9GhOS+E13MSBQ+Zg==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:Hyr8vsSoAidxWyPbgNY5Z5sN0XQne9GspRYNOi61jZ38Tf2y3eZMEwq14Lb06oI=,iv:vSBHNllDbxjS3chG8PPsbtRsKVw/1QSZ7N5bQHki2+0=,tag:Jou32LLjyw5qEBkiQGK+Cw==,type:str]
    #ENC[AES256_GCM,data:aktQ/7ZOnUCYsLxXtO8IuFMSHjoZiMxrG3ZFwr/prx1J+6g1Y8eJ46oM0f5VVCwuCVufTgtASZkOSneBFsTQzbUbelIKE3U=,iv:YQvA8mJDFImKjq71BBWvlscG9f/MYcX36VG1pW7UeBY=,tag:yiXV8nJHxFfvsJBbC6HHmA==,type:comment]
    #ENC[AES256_GCM,data:p8OPjKzoZCKPUsIXdPXcdcFcqC/ztAyfmhuVlHTo866fsDIaOl1JtZ+FOc4A3VnuzlZLdER+,iv:IB6pffBQw7To3yC4DTppLuFqb/y8/FnAEkF9TrFGHbA=,tag:kIBHzkz+Wwt4qPA0iXUDWQ==,type:comment]
    #ENC[AES256_GCM,data:7ejYbteMvVkRnFVDDIFuCh2YQLViKXCwshq5LzPK6TwwePY=,iv:ejngL7B1F7c3Xz0gQ+99YFpNbsbAsegnMtIjfjyFhdA=,tag:JGRKeF6t6oDfXc4VP6hTvw==,type:comment]
    #ENC[AES256_GCM,data:hbpOGdgIlqkewwa+XY9YoOPhRozCSaMJazRSHJEHw9p5NVXB/OdP,iv:0yFpv1924UXNGXSQPE/+w1mOhFQOhhHpSjIOImo6Yws=,tag:BP50TxrgBnHn1hOkyxi0tg==,type:comment]
    #ENC[AES256_GCM,data:RCevCCHoBsksGwBaqas=,iv:l+F5mpwJ/+IpXV4idRJEIZ9K2VIsptFo6sfC51DdJa8=,tag:IqiQxOo89onARuQavUcCiQ==,type:comment]
    PODNET: ENC[AES256_GCM,data:Hzcmijs+U29zyJdReQ==,iv:TKneXkA8QWLtLz6X+gb8+TwVqX2PctaH6IGSAlpYHL8=,tag:QaLThHEwon4lJKEaVvfAkQ==,type:str]
    SVCNET: ENC[AES256_GCM,data:xI/pclHyB15FfsGNlA==,iv:AAmSsBA3Q0Lqo7mh3sZOBi2QGPwJOppiIxYs6RB+h9s=,tag:xQ1mbNedwAPZDr4VniWF/w==,type:str]
    #ENC[AES256_GCM,data:OPuXkQxZXOGVMg==,iv:fJ1lyTLmk/N05BP6HUv/qneyFeUl7Y3rcFGiBM8QwMk=,tag:nGVjn/DxD0uJmE7rJKullQ==,type:comment]
    #ENC[AES256_GCM,data:y7Yot++/G24=,iv:J61mkgrEcMSxonKG4tkc1KK3yqBp/n0AcxBq9wIJlvg=,tag:36kX4GiMfEupYCcGTcm/qw==,type:comment]
    MASTER2IP: ENC[AES256_GCM,data:Y1Ai8mgCNoAWoq7vNTM=,iv:ExsGIo/QFP/NYpKfu992O9YreUbmLg2mk0XXNwqSiI8=,tag:hGq3f+7+V605g38ozMlydQ==,type:str]
    #ENC[AES256_GCM,data:BBJzJ+kKAtEcgA==,iv:PJnGFlLzs46qFiU5L9oxedQ+KxSbAfvV3x6IC6SibJE=,tag:OBCJ3hhmtDG7bBsUUgfvcA==,type:comment]
    TRAEFIK_IP: ENC[AES256_GCM,data:moaeutVHCjyWZj41kQ==,iv:czeFoiP0LRZfH12rijU9F3WB31tZ8U1UUdEyQKT1x4U=,tag:APGkxpu5zATjPccvzqfUCA==,type:str]
    HA_IP: ENC[AES256_GCM,data:GipeXAKDetSTAUHiDg==,iv:TTokyHDT4fPdoOcW3KQBHvanoAZkIlds4DZ5Z54t/3o=,tag:NfBw2AdTTWudRwQUU4uLVw==,type:str]
    BLOCKY_IP: ENC[AES256_GCM,data:uWVNv8DnwjwQuSydRw==,iv:MyP8C+MQvsX46wHOUFW+bu9+KlWFX9ABRsQpJP4Su+c=,tag:1ioj8G0XVcpvgcIVOxlI/A==,type:str]
    PLEX_IP: ENC[AES256_GCM,data:up5fFZZHSM+Ts2snyEg=,iv:deD18j6CD2aGmJVZg1qfppYKK5jT6dV1ZVnwQT0Diso=,tag:8tc8/R1e3r8CgLs6NiwzpQ==,type:str]
    TRUENAS_IP: ENC[AES256_GCM,data:YfU32wya6sHYu4+iimQ=,iv:VXjoQlTmwMIO/JVjTI29g/sZB5dGU64AS1fvFnAQBDM=,tag:zxu8h1bZfBc/8t3QYRJh6Q==,type:str]
    MAIL_IP: ENC[AES256_GCM,data:tzbAQ1HLKo1iT2pjTDE=,iv:YbEnFS9Tph/VNaHFVlxxEpq/eW9Gl4f7rkPG1/esKCY=,tag:FcjxYqeYmP5MhzsczGe9mA==,type:str]
    #ENC[AES256_GCM,data:R3SMuqpi,iv:l7hRRvNGmMF2SE/G8YO9anYuO6Tmw9Ddy6hJ2hwGISE=,tag:fr4j3MgfK54eEl4hC+kK3w==,type:comment]
    CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:vEpdgMZSIlbVGDpRj/C3uePsmPHBl0RLRARhn/dv9yZi85DBH8KBtg==,iv:eN2qKgfH0a3X91T/vBECTxsz2KXhr9OdYmTC1ZPifos=,tag:iil3v8FjTeMAl6sSKA4F0Q==,type:str]
    EMAIL: ENC[AES256_GCM,data:Rfg4LJ6zasohtJIw3gZR/6hBa1B8o2G9ONb1ntVRfw==,iv:foj5Ey0MdVh3DNIOqMRHcTmHPWCGbZ98hcE8bPbVT5Q=,tag:fgKHKBY3z15Yv9N9tYBzvA==,type:str]
    #ENC[AES256_GCM,data:Bqw4lY/p784=,iv:MffMIGyl+N/EssXoreTEpDPnFbroe7qd9rhDPCvPgpk=,tag:b4o2zVrmPo3aE2Jr4Pbing==,type:comment]
    BASE_DOMAIN: ENC[AES256_GCM,data:4S0wCWH7O5EdY6HJdw==,iv:SNSSNUgKWPvrFtZzIMciMMs3ziHvMKEpAW3fm5Ip4P4=,tag:0rVapqZ0KPSlALyX8g8xRQ==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:MunSPQ==,iv:n/1dNm3RCHrRehihbXxoMMckwKui5xXLFMXPK73x4yU=,tag:S8oWpH5YTn+iFSxcDgHj+Q==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12cqk6j6886czzr7l93xldt5qjxrl473336mmpe4dzrmj7f8jg3zs6vaqek
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKSWk3VEVPaVhnaFFxRlpt
            NkhEWTF4Qnc1WnppZGd6MC9ERFNPRy9JdDBVCllUN0N6L1Zsd0dhaDRFVEQyWFVC
            bnQ5NHd3ZHdsQWpmRE9aU1VobGZiaWsKLS0tIG1mOGxwVno4MTAyNXFZazAzbC9X
            NlpKREJETThPbG9nSzV0TURVTzc3a28KMsPUEMCpjxqihCOzVr/5gM2q/fd/+htB
            wK9v9bcfnnnC0BMKtUHlABqR0BwRpS/qO1+0/KvXdZhVVmRa05Jtrw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-26T15:52:31Z"
    mac: ENC[AES256_GCM,data:htwelKVLrXWqAszJ7IzZTd+qmOWp9otPfVGHyTZ0hdA0rHjGzq52ta4RZkRuEMF9g29jM8+ORISoWZyLWRpPViMY/urtFd91JRZLygdQlWDQBOcWPmfsT9RfMaKz34E9Tnkmyq74W7U3VwT9HtmkW+5HRXaFplMxcrmndPV6F5A=,iv:hUuOhzbeJZZ+3X7qY44AAaXGaZXC1W2wLaKsQJuTkR8=,tag:euWla5LdFIPE8R4Um9YoXg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
