apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:ipVY0zQlb2c68+5IsC6b/H9waffOmp9SQNPVHHFAjujO8FQnQ64afswT+CYhjMh9of2uXIaeve0vp3XsuyHD9zCbRS+CPuzekibQ8m1w83brODj/1tG3mDMpC5MmjYpSy6KaLoFsHWrq51mqEWGYXqK0cobWFMCrhlTMcW7VAiPgmw+jJoTXyniLA2UaYfLj4L/QH3SJaNd/nZiu3wffWcsuhLLveu9h23MA9L+JbM0MfeQbRF+jhjCNtdRmow5q6eeaAUT4oBdZ/kGBUNewT8pv/aymdaJRzeARAKLyvmgv4S1jC7k7wlOykrLAFjqZJdKbnGSe5itlzn3aM1tscXRxQAlXQ51GDy8MlqJs9wCfljWeWqLr2f+pRkYTM+8z,iv:qi5ah2uUA1qNmNcK2gt+o68flYAxOK+JMaVqNu+J0gk=,tag:WjW3rHz/yhU4wUqAUQnYug==,type:str]
    identity.pub: ENC[AES256_GCM,data:rwoXCNBKxnAVsj6BKgZ5nrot0pRHePnxTZaolEgIdfyfFAtyHAAAnbWmY+XLbyZVYxfJstdJ6kiNqVBzp8yXXfd9oBUTN8Ksmb4oF22SgS+vDhwmKfSloSpGs13oUqVaTJ4AoCIt7xMkZWdmnm+Yph/dQM2so5gD0OJLVvAfSBn68sU4oHMibULX1KtPclikCuLyO0j1M8Fiu5INSfZJcOSRp2bKnXBT5ZLrBiaUKBCI1T8JELduzHgrnU0b17M/kUNaCT8tPw+tZ0w/eQ==,iv:ktGrOQDnefSBi8Q47jmD7wWyyL97h1la8i4RJKexels=,tag:/oAuF5Rj69tfuX3yVe0f0A==,type:str]
    known_hosts: ENC[AES256_GCM,data:SOYXyGl19aBZXg/c8h+1bpqBXkYBZIhATVEtSyfwTNfjeMO5quuNq5xIcqzrn2wJx+5h45JC5fYcS52Uqd+2w1qLJHm42mqiMJQtwhMFPXqyWYds0A2UI/5Qj7MkPbmND3Oux0J3Hc0NCFRMlXzX3hurxFZWfPYilBNT8akboelsb/z/J64cvhRubiMi6aw5/lP3lXZiPl4L2LtiWAP/cDTnVcq3vj3bvHFM,iv:pCo5ofYL2efldvuHPiuz8+dQcR12Iz+38hCDtkPPjwI=,tag:1wk3O7yqHSkWPvDefnZxqQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12cqk6j6886czzr7l93xldt5qjxrl473336mmpe4dzrmj7f8jg3zs6vaqek
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwUjJQekZ5RzdYbG1pN2du
            Zm54eWR2MjdwWTBBV2RUV1JseUtUdEh3bUhVCnljanpIMkk0QjZ6cVNCamlJbFpC
            M3BEemtRYklUSEY0QU5rZW4xRU9POTgKLS0tIHBwYzlOVXFtdXJoalZOTXpyV2Zs
            TDV3TjMrUlJWVERENmM2VGlJODAzMXcKgmyraBe037CQpvQjyPpqEZXyZ8tNOiNc
            1AssYB4rS/dtFU+c69DOs7KIMdiD4gGrODsV0smRTuk70I2uJ8N0gw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-26T15:28:34Z"
    mac: ENC[AES256_GCM,data:yKcR8Db71a4SkbGkUcO84YdN/gtrMf+FRHNEPb404031UI/QHx7HNwVuYn/DQVLh4SI2vtglxwSa/LIXyWMwWEz+/+PVoom6EOTyqeEHwc3uimD5czhZ9n4tWmmXKU5RHyC9NVJDbzmn3zuAXQTMi5lH6uqzUj4Jb96wPcCOoGY=,iv:/oVogwvvmMN/DGhqe+6y1gflAEa8WLqFbN58jpxmkno=,tag:7IHrDq3Ab+KRw32vC4DTwA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
